# Generated by Django 4.2.13 on 2026-06-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='normalize_mode',
            field=models.CharField(default='none', max_length=16),
        ),
    ]
